### ISSUE TITLE
恐「驚」出現九調

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#108]
987
逐家看有人食六粒，攏恐驚家己食輸人，嘛攏叫六粒來食。
Ta̍k-ke khuànn ū lâng tsia̍h la̍k lia̍p, lóng khióng-kiann ka-tī tsia̍h su--lâng, mā lóng kiò la̍k lia̍p lâi tsia̍h.

「驚」音檔是唸成9調了，強化語氣？還是疑似合音？

**Comment by sih4sing5hong5** [comment]
Thiau-kang第9調

**Comment by naphing** [comment]
按呢就漢字臺羅攏拍第九調囉

**Comment by sih4sing5hong5** [comment]
好，攏第9調

naphing <notifications@github.com> 於 2019年1月25日週五 下午6:17寫道：
