### ISSUE TITLE
教典用字莫收例句

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#109]
#107 
例句內底可能有地名，hia-ê 地名的漢字有可能照華語寫。

**Comment by a8568730** [comment]
原本這个議題是欲閃例句內底收的地名。
毋過，發現教典直接共基隆的基［ke1］加入去詞目總檔內底，

11 | 基 | ke<白> 
-- | -- | -- 
12 | 基 | ki<文>

按呢，基可能就閃袂掉矣。

**Comment by sih4sing5hong5** [comment]
好--ah
