### ISSUE TITLE
狀聲詞「哈哈哈」標記

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#111]
1001句
「哈哈哈！恁遐爾愛食，我當然會閣來lōo！」漢鍾離笑甲誠無自然。
"Hah hah hah! Lín hiah-nī ài tsia̍h, guá tong-liân ē koh lâi lōo!" Hàn Tsing-lî tshiò kah tsiânn bô tsū-liân.

聽起來口語調是2,4,3 怎標？

哈本調有ha/hah

**Comment by sih4sing5hong5** [comment]
照 https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/48 ，而且假設語氣詞攏袂變調

> 聽起來口語調是2,4,3 怎標？

`Há--hah--hah`


> 聽起來口語調是2,2,4,3 怎標？

假設語氣詞攏袂變調
`Há há--hah--hah`

**Comment by naphing** [comment]
順問
1012
邊仔彼一寡人聽著少年家按呢講，攏笑甲嘻哈叫。講：「這个人頭殼定著有問題！」
Pinn--á hit tsi̍t-kuá lâng thiann-tio̍h siàu-liân-ke án-ne kóng, lóng tshiò kah hi-hah-kiò. Kóng: "Tsit ê lâng thâu-khak tiānn-tio̍h ū-būn-tê!"

「嘻哈」應是狀聲詞，老師念3,3調，這該怎標？

**Comment by sih4sing5hong5** [comment]
> 順問

以後開新issue，標題kah內容才會仝款~


> 1012
> 邊仔彼一寡人聽著少年家按呢講，攏笑甲嘻哈叫。講：「這个人頭殼定著有問題！」
> Pinn--á hit tsi̍t-kuá lâng thiann-tio̍h siàu-liân-ke án-ne kóng, lóng tshiò kah hi-hah-kiò. Kóng: "Tsit ê lâng thâu-khak tiānn-tio̍h ū-būn-tê!"
> 
> 「嘻哈」應是狀聲詞，老師念3,3調，這該怎標？

頂頭`哈哈哈`是語氣詞，所以kah別ê詞無仝。
`嘻哈叫`就照一般詞回推本調`hī-hā-kiò`

**Comment by sih4sing5hong5** [comment]
hackmd--ah，

@naphing 若看過就 close
