### ISSUE TITLE
漢字欄與臺羅欄標點符號對應

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#113]
1.半全形括號
參考867
對遮通知這擺收入來的，就是我這十冬踮小說這个文類攏總的成果（假使我無落勾來講）。
Uì tsia thang tsai tsit pái siu--ji̍p-lâi--ê, tō sī guá tsit tsa̍p tang tiàm siáu-suat tsit ê bûn-luī lóng-tsóng ê sîng-kó (ká-sú guá bô làu-kau lâi-kóng).

2.人物對話裡的話，標點符號『』佮 ' '  要對應
參看1018
少年家聽一下掣一趒，講：「當時仔你是神仙！阮真正是『目睭擘無金』。毋過，佇遮爾濟人當中，你是按怎會選著我咧？」
Siàu-liân-ke thiann tsi̍t-ē tshuah-tsi̍t-tiô, kóng: "Tang-sî-á lí sī sîn-sian! Gún tsin-tsiànn sī ‘Ba̍k-tsiu peh bô kim’. M̄-koh, tī tsiah-nī tsē lâng tang-tiong, lí sī-án-tsuánn ē suán-tio̍h guá--leh?"

**Comment by sih4sing5hong5** [comment]
半形引號有4種


| |  孤 | 雙 |
| -------- | -------- | -------- |
|有方向 | `‘a’` | `“a”` |
|無方向 | `'a'` |  `"a"` |

我查英語ê慣勢，攏是用有方向--ê
- https://practicaltypography.com/straight-and-curly-quotes.html
- https://data.grammarbook.com/blog/commas/quoting-a-question-within-a-question/
- https://www.grammarly.com/blog/quotation-within-quotation/

教典用無方向--ê
```
   537  ./例句.csv:6382,6052,8324,1,人講「食緊挵破碗」，你著照步來。,"Lâng kóng ""tsia̍h-kín lòng-phuà uánn"", lí tio̍h tsiàu-pōo-lâi. ",人家說「吃得快容易打破碗
」，你還是要按部就班。
   541  ./例句.csv:12841,12726,16998,1,伊按呢做根本就是「一隻牛剝雙重皮」，實在
誠可惡！,"I án-ne tsò kin-pún tō sī ""tsi̍t tsiah gû pak siang-tîng phuê"", si̍t-tsāi tsiânn khó-ònn! ",他這樣做根本就是「一頭牛剝兩層皮」，實在很可惡！
   543  ./例句.csv:13460,13337,17779,1,人講：「驚某大丈夫，拍某豬狗牛。」你著愛
好好仔疼惜恁牽手才著。,"Lâng kóng: ""Kiann bóo tāi-tiōng-hu, phah bóo ti-káu-gû."" Lí tio̍h-ài hó-hó-á thiànn-sioh lín khan-tshiú tsiah tio̍h.",人家說：「怕老婆是大丈夫，打老婆是豬狗牛。」你要好好疼惜你的老婆才對。
```

Bóng報用有方向--ê

**Comment by sih4sing5hong5** [comment]
[Wiki](https://en.wikipedia.org/wiki/Quotation_marks_in_English)講有ê軟體會轉做有方向--ê，代表較佮意有方向--ê
```
Quotation marks are written as a pair of opening and closing marks in either of two styles: single (‘...’) or double (“...”). Opening and closing quotation marks may be identical in form (called neutral, vertical, straight, typewriter, or "dumb" quotation marks), or may be distinctly left-handed and right-handed (typographic or, colloquially, curly quotation marks); see quotation mark glyphs for details. Typographic quotation marks are usually used in manuscript and typeset text. Because typewriter and computer keyboards lack keys to directly enter typographic quotation marks, much typed writing has neutral quotation marks. The "smart quotes" feature in some computer software can convert neutral quotation marks to typographic ones, but sometimes imperfectly. 
```

**Comment by naphing** [comment]
有方向性，長得「逗號」的，不管是臺羅輸入抑英半攏歹處理，按不出來咧

**Comment by sih4sing5hong5** [comment]
> 有方向性，長得「逗號」的，不管是臺羅輸入抑英半攏歹處理，按不出來咧

按呢就攏拍無方向ê，尾仔才閣用程式轉

**Comment by sih4sing5hong5** [comment]
> > 有方向性，長得「逗號」的，不管是臺羅輸入抑英半攏歹處理，按不出來咧
> 
> 按呢就攏拍無方向ê，尾仔才閣用程式轉

改做：
若新拍ê，就拍無方向。若已經拍好有方向--ê，就保持有方向

**Comment by sih4sing5hong5** [comment]
hackmd--ah
