### ISSUE TITLE
佳哉仔佳哉

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#127]
#106 

佳哉仔佳哉，到甲欲暗仔，有一个收歹銅舊錫的阿姨，看in猶閣媠媠咧，就隨共抾(khioh)走。
佳哉a佳哉，到甲欲暗仔，有一个收歹銅舊錫的阿姨，看in猶閣媠媠咧，就隨共抾走。

> 好命a好命
> naphing: 1 7 1 1 7 
> 佳哉a佳哉
> 秀容:3 1 1 7 3
> 好勢a好勢
> naphing:1 1 1 1 3
> 結論: 第2字合(hah8)仔前變調，所以是仔 
> 1/28 Naphing已經改

**Comment by sih4sing5hong5** [comment]
hackmd--ah

**Comment by naphing** [comment]
仔在這狀況算中綴嗎？如果算的話要連？
例如：清氣清氣   清氣仔清氣

**Comment by sih4sing5hong5** [comment]
應該是--ooh，連做伙好--ah

**Comment by naphing** [comment]
但中綴多半是A仔B的名詞型態呢！看盧廣成的「臺灣閩南語概要」舉例全是名詞

**Comment by sih4sing5hong5** [comment]
教典無這種例
```
~/git/moedict-data-twblg/uni$ grep -E '([a-z0-9]+)\-á\-\1' -r .
```

**Comment by sih4sing5hong5** [comment]
TJ是連寫，`á 1 `ê `2.疊詞`
![掃描的文件](https://user-images.githubusercontent.com/5996555/59495853-cc115b80-8ec2-11e9-8858-216339286020.jpg)

**Comment by naphing** [comment]
決議，全連，立馬改
