### ISSUE TITLE
Nov 3, 2018_311.wav 後壁有電子音

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#13]
210 | Sony手機仔敢有好用？ | Sony tshiú-ki-á kám ū hó iōng?
-- | -- | --

**Comment by a8568730** [comment]
![image](https://user-images.githubusercontent.com/6355592/51364208-58874000-1b16-11e9-8017-a03359e511b0.png)
Dropbox/母語/語料/TTS 語音合成錄製/Nov\ 3,\ 2018/英語/Nov\ 3\,\ 2018_311.wav

應該是直接共切掉就會用得。

**Comment by a8568730** [comment]
Nov 3, 2018_311_removeTail.wav
秒數：0 - 3.7494101666292377

**Comment by a8568730** [comment]
@naphing 阮已經共後壁的聲切掉--looh，若你聽了無問題才麻煩共狀態6提掉。
![image](https://user-images.githubusercontent.com/6355592/51536941-206e5d00-1e88-11e9-911c-155722e49098.png)
