### ISSUE TITLE
618 你拍咳啾愛用手去掩咧őo 對齊錯誤[字：őo őo]

### ISSUE THREAD

**Issue by a8568730** [Sui-Siann-Dataset/Sui-Siann-Dataset#132]
618
你拍咳啾愛用手去掩咧őo，若無ba̋i-khín會四界飛。
Lí phah-ka-tshiùnn ài iōng tshiú khì om--leh őo, nā-bô ba̋i-khín ē sì-kè pue.
[字：őo őo]

**Comment by sih4sing5hong5** [comment]
請na-phing 漢字ê改做`őo`

**Comment by naphing** [comment]
原來是字型不一樣Orz
看甲目睭脫窗嘛看袂出來

**Comment by a8568730** [comment]
őo őo
頭前：\u006f\u030b\u006f 
後壁：\u0151\u006f
鬼才看會出來
