### ISSUE TITLE
CSV校對漢字欄詞之間的多餘空格

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#134]
如附圖，列8、9、10、13、14
漢字欄偶有句子詞跟詞之間空格，要不要處理掉？
![image](https://user-images.githubusercontent.com/35830498/52758445-4a5c0f00-3043-11e9-9725-ef17e381e966.png)

BTW,阿不拉好亂（一語雙關）

**Comment by a8568730** [comment]
Őo~~這是因為原本中教大彼爿有標本調（#符號），阮取代的時無處理好勢。嘛害老師直直頓蹬。:$
原本的：廣東#片#，
阮取代：廣東 片 ，

建議做法：選漢字欄，空白直接共取代掉。閣來選羅馬字欄，共兩个空白的取代掉。

**Comment by naphing** [comment]
瞭解，隨來改
