### ISSUE TITLE
漢字有書名號《 》毋過英語無書名號

### ISSUE THREAD

**Issue by a8568730** [Sui-Siann-Dataset/Sui-Siann-Dataset#148]
目前語料庫會寫做

頂期《經濟學人》...
Tíng kî “King-tsè Ha̍k-jîn”

毋過根據 #113 的標點符號表，英語是無書名號的，是寫趨趨的。
頂期《經濟學人》...
Tíng kî _King-tsè Ha̍k-jîn_

**Comment by sih4sing5hong5** [comment]
https://zh.wikipedia.org/wiki/%E4%B9%A6%E5%90%8D%E5%8F%B7#%E5%85%B6%E4%BB%96%E8%AA%9E%E8%A8%80

英文沒有書名號。書名直接以斜體字來表示，如 _Harry Potter_。而以引號表示篇名，如 “The Sentinel”。

日文的書名號為雙引號『』，並不使用雙角號《》[註 1]，篇名則使用單引號「」表示。

**Comment by sih4sing5hong5** [comment]
不管`、《 xx》` 抑是`〈xx 〉` ，羅馬字攏用`“xx”`

**Comment by sih4sing5hong5** [comment]
加入教典用字--ah
