### ISSUE TITLE
1515 好nooh

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#162]
1515
好！喔。
Hó! Ooh.

實際發ho2--nooh
在「連字符使用規則」（拼音手冊p.57）例子有：ho2--noh! 好喏，但教典查不到「喏」字！
怎解？

**Comment by sih4sing5hong5** [comment]
就寫`Hó--nooh`
漢字`好--nooh`

**Comment by naphing** [comment]
> --nooh
@sih4sing5hong5 
漢字欄輕聲符留咧？

**Comment by sih4sing5hong5** [comment]
> > --nooh
> > @sih4sing5hong5
> > 漢字欄輕聲符留咧？

歹勢，漢字改`好nooh`

**Comment by naphing** [comment]
已經處理，關
