### ISSUE TITLE
有sánn句，原本切了走精

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#165]
@naphing  鬥記錄一下

**Comment by naphing** [comment]
> @naphing 鬥記錄一下

猶未拄著，是音檔錄了傷清氣，電腦攏判斷正確？XDDD

**Comment by naphing** [comment]
2143、2144、2148、2150、2154、2155
攏是切外語詞做一句時切無好，猶未重新併句重切

**Comment by naphing** [comment]
803_Hillary Clinton欲終結大量監禁    篇
2175、2184、2186

**Comment by naphing** [comment]
804_種族屠殺的教訓 篇
2195、2196、2198、2203、2206、2207

**Comment by sih4sing5hong5** [comment]
切無好的用另外的狀態來標記，尾仔我才來檢查

**Comment by naphing** [comment]
> 切無好的用另外的狀態來標記，尾仔我才來檢查

好，語料狀況開一類予「切音無好」

**Comment by sih4sing5hong5** [comment]
我有修對齊ê程式，外語會切較準--leh
請問是全部`3 切音無好`攏重切？
`5 台英混用`ê敢著重切？

**Comment by naphing** [comment]
處理「切音無好」的就好

**Comment by sih4sing5hong5** [comment]
Tng-tih 走
```
from SuiSiannAdminApp.models import 句表
for ku in 句表.objects.filter(語料狀況__id=3).order_by('id'):
    print(ku.id)
    ku.重對齊()
```

**Comment by sih4sing5hong5** [comment]
重對齊好--ah
