### ISSUE TITLE
切句傷幼予畫面歹校對

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#166]
譬如1712的例，原本切到31句，予校對網站畫面傷長愛徙來徙去。淡薄仔歹處理
是講，只有燒肉粽一个音檔傷濟句的情形？目前我咧重排重切，予逐句加長淡薄。
![image](https://user-images.githubusercontent.com/35830498/53311000-00e4ad00-38ea-11e9-968b-89b5630af60a.png)
![image](https://user-images.githubusercontent.com/35830498/53311016-09d57e80-38ea-11e9-94a7-b9efc7e4e6c6.png)
![image](https://user-images.githubusercontent.com/35830498/53311032-1a85f480-38ea-11e9-8bca-850d7471d486.png)

**Comment by sih4sing5hong5** [comment]
幾句以上會歹校對？

**Comment by naphing** [comment]
> 幾句以上會歹校對？

5列OK，10列以上開始拉畫面上下跑

> 幾句一組會較好？

一列約3-5句OK
有時覺得這麼長句如果直接一音檔撥到底，邊聽邊校我自己按pause會不會好操作點啊？

**Comment by sih4sing5hong5** [comment]
> 有時覺得這麼長句如果直接一音檔撥到底，邊聽邊校我自己按pause會不會好操作點啊？
因為愛看羅馬字，所以按呢應該較oh校對甲真詳細？

**Comment by sih4sing5hong5** [comment]
#174 好--ah
若等咧開會討論了後無問題，就來上線
