### ISSUE TITLE
 被Naphing重切搞爛的句

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#167]
1712，頭句音沒對，重切還是一樣 #168

**Comment by sih4sing5hong5** [comment]
1712  一開始敢是著--的? 因為我看kaldi 共 頭家娘 當作 SIL

**Comment by naphing** [comment]
一開始的版本是將「頭家娘」切去第二句，無濫去頭前句。
重切版的第七句原本kaldi照原稿鴻文佮Hann9切開，重切了顛倒併做伙Orz

**Comment by sih4sing5hong5** [comment]
切無好的用另外的狀態來標記，尾仔我才來檢查

**Comment by sih4sing5hong5** [comment]
攏佇 #165  討論
