### ISSUE TITLE
2252 袂當「lose」任何一條訊息

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#175]
2252
袂當lose任何一條訊息
Bē-tàng lose jīm-hô tsi̍t tiâu sìn-sit

照老師發音改拼做「loo3-su2」可否？

**Comment by sih4sing5hong5** [comment]
好，因為毋是英語唸法，而且羅馬字寫會出來，就寫羅馬字

**Comment by sih4sing5hong5** [comment]
hackmd--ah
