### ISSUE TITLE
2278 地「藏」菩薩

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#177]
2278
地藏菩薩本願經
Tē-tsōng phôo-sat Pún-guān-king

藏tsong7、tsong5
老師念做tsong2，NG去？

**Comment by sih4sing5hong5** [comment]
https://www.youtube.com/watch?v=UPyPXw160DQ&t=5s
口語第7調

https://itaigi.tw/k/%E5%9C%B0%E8%97%8F%E7%8E%8B
tē-tsông-ông/tuē-tsông-ông


結論: NG

**Comment by naphing** [comment]
處理好勢
