### ISSUE TITLE
2289 「pué會」意思？

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#178]
2289
女朋友佮前女朋友攏出來pué會，
Lú-pîng-iú kah tsîng lú-pîng-iú lóng tshut-lâi pué-huē,

我照老師發音記詞，請幫我查原文是寫「？」會
敢會是「賠會puê-huē」

**Comment by a8568730** [comment]
[潘科元台語文理想國-台語詞「撨代誌」相關个講法](https://blog.xuite.net/khoguan/blog/61966350-%E5%8F%B0%E8%AA%9E%E8%A9%9E%E3%80%8C%E6%92%A8%E4%BB%A3%E8%AA%8C%E3%80%8D%E7%9B%B8%E9%97%9C%E4%B8%AA%E8%AC%9B%E6%B3%95)

4. 小寡仔代，毋免著掰會[pué-huē / pé-hē]到按呢。（掰會 是爭論、爭執，嘛有講「掰手面」）

--
台文華文線頂辭典(總共4筆)
白話字 | 漢羅台文(白話字) | 教育部羅馬字 | 對應華文 |  
-- | -- | -- | -- | --
póe-hōe | 掰會 | pué-huē | 理會 | 詳細
póe-hōe | 掰會 | pué-huē | 解釋誤會 | 詳細
póe-hōe | 掰會 | pué-huē | 說明 | 詳細
póe-hōe | 掰會 | pué-huē | 辯明 | 詳細

Maryknoll台英辭典(總共1筆)
白話字 | 教育部羅馬字 | 對應華文 | 對應英文 |  
-- | -- | -- | -- | --
póe-hōe | pué-huē | 弄清 ,講明白 | make (something) clear, put (something) straight | 詳細

**Comment by naphing** [comment]
瞭解，隨來改，感恩勞力
