### ISSUE TITLE
叫教育部改 ho2--noh! 好喏

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#187]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/162#issue-413331947

 在「連字符使用規則」（拼音手冊p.57）例子有：ho2--noh! 好喏，但教典查不到「喏」字！

`noh`無合台羅ê音

**Comment by naphing** [comment]
寫矣，順紲sa-bi-suh一个予in

敬啟者您好：
兩个羅馬字拼音方案手冊內容的問題欲請教
1.羅馬字手冊內容第57頁五、輕聲詞之標示，語尾助詞bô--noh（無喏）使用「喏noh」敢有錯誤？
佇辭典頂查無「喏」字，而且根據音節表嘛無noh的音。
是毋是愛寫做「無nooh/bô--nooh」

2.手冊第60頁連字符分類說明，四、形容詞第（一）形容詞與所修飾的名詞分寫。例寫「有錢人ū-tsînn lâng」。
佇辭典煞查著「有錢人ū-tsînn-lâng」是連寫，敢有矛盾？請確認，多謝。

您可以依據您的信件編號：201903050031，至教育部網站查詢目前信件的處理情形，謝謝您的來信！

**Comment by naphing** [comment]
回批
邱小姐：您好！
　　您於108年3月5日寄至本部部長信箱的信件，我們已經收到了，謝謝您的來信。有關您詢問「臺灣閩南語羅馬字拼音方案」手冊內容的問題，向您說明如下：
　　手冊頁57五、輕聲詞之標示語尾助詞bo--noh（無喏）；頁60四、形容詞（一）形容詞與所修飾的名詞分寫。原用例：「有錢人」為一完整詞，意為「富有的人」，應寫為「?-tsinn-lang」，兩者查屬誤植，將配合修正。
　　考量《臺灣閩南語常用詞辭典》近年已陸續修正其內容，相關資源實須配合辭典修正情形全面檢視其字音之一致性。為整合資源，並求內容更為正確、周全，與連字符有關的資料，將請相關學者專家進行審查確認，現正進行相關流程，惟因內容的改動，需完成相關程序，始得公布，故恐需一定時程，懇請見諒。修正完竣後將於「教育部語文成果網」（https://language.moe.gov.tw/）更新。

**Comment by naphing** [comment]
所以以後校對一律：漢字臺羅攏寫--nooh

**Comment by sih4sing5hong5** [comment]
多謝你kià-phue~
