### ISSUE TITLE
2637、2639 恁「爸」

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#189]
2637
霞的， 恁爸明仔載欲la̋i臺北。
Hâ--ê, lín pâ bîn-á-tsài beh la̋i Tâi-pak.
2639
阮公司派我佮阮主任去， 恁爸若無佇咧， 你就毋通拋拋走。
gún kong-si phài guá kah gún tsú-jīm khì, lín pâ nā-bô tī--leh, lí tō m̄-thang pha-pha-tsáu.

原稿＆老師是念pa5，不過個人覺得有點怪啦，講恁pa5多是第一人對第二人描述「你爸爸...」，恁pe7是第一人對第二人的自稱。
詞彙跟音節上雖無誤，但就是一點怪，如何解？

**Comment by sih4sing5hong5** [comment]
（我是bunli）

> 2637

你的意思是合句法，但是不合語意？
照你的說法看來，底下兩個語法語意是ok的。
阿霞，恁爸（pa5）明仔載欲la̋i臺北。=> 從稱呼猜測是親戚/外人，向阿霞提及阿霞的爸爸
霞的，恁爸（pe7）明仔載欲la̋i臺北。=> 從稱呼猜測是爸爸本人，向阿霞提及自己

那有沒有可能是媽媽向阿霞提及爸爸？
霞的，恁爸（pa5）明仔載欲la̋i臺北。

> 2639

同理，如果是小明媽媽向小明提及小明爸爸，這樣有合理嗎？

明天一併跟老師討論也是ok的，或許真的是尷尬的句子，那就可能要重錄。

**Comment by naphing** [comment]
喔我撈影片來聽了是pa5
https://youtu.be/lfwODaBsSzI?t=525

**Comment by a8568730** [comment]
結論：OK，維持 pâ
