### ISSUE TITLE
斷句原則

### ISSUE THREAD

**Issue by a8568730** [Sui-Siann-Dataset/Sui-Siann-Dataset#191]
參考 https://github.com/Sui-Siann-Dataset/Ungian-Lun-Bun/issues/5

# 斷句

有一个完整語意就可斷句。

### A原文
語詞搭配(collocation)是學習語詞按怎使用真好ê工具，這會tàng透過對語料ê互訊息(mutual information) kah相關度(correlation) ê統計來得著，m̄-koh mā會產生bōe少無必要ê資料(noise)。

### A拆做
語詞搭配(collocation)是學習語詞按怎使用真好的工具,

這會當透過 對語料的互訊息(mutual information) 佮 相關度(correlation) 的統計來得著, 毋過嘛會產生袂少無必要的資料(noise)。

### B原文
語料庫tō是khǹg語言材料ê倉庫，[Ng&Li 2002 p1]伊會sái講是人類所講、所寫ê語言文字ê一個樣本，透過這個樣本，咱thang透過語料庫了解這個語言、文字ê使用情形。二十世紀60年代，英文ê語料庫開始建立，90年代，華文ê語料庫mā開始tī台灣、中國等所在建立。台文ê起步khah òaⁿ，一直kàu這(21)世紀chiah開始。

### B拆做
「搭配」這个詞, 台語閣會使講「參佮」、「照佮」、「sann 佮」、「配搭」、...等等, 毋過為著佮華語詞對應, 所以採用「搭配」。

語料庫就是囥語言材料的倉庫, 伊會使講是人類所講、所寫的語言文字的一个樣本,

透過這个樣本, 咱通透過語料庫了解這个語言、文字的使用情形。

二十世紀 60 年代, 英文的語料庫開始建立。

90 年代, 華文的語料庫嘛開始佇台灣、中國等所在建立。

台文的起步較晏, 一直到這世紀(21 世紀)才開始。

**Comment by sih4sing5hong5** [comment]
hackmd--ah
