### ISSUE TITLE
整理NG句 做 錄音稿

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#192]
- [x] NG 句列出來
- [x] NG ê 所在 加底線

加 一ê 狀態： ` NG句，有準備koh錄音`

**Comment by naphing** [comment]
欲另外一个檔案？ODT？抑是直接列佇ISSUE內

> * [ ]  NG 句列出來
> * [ ]  NG ê 所在 加底線
> 
> 加 一ê 狀態： ` NG句，有準備koh錄音`
^^^^^^^^^^^^^^^^^^^^^^^^^^^看無，佇佗加狀態

**Comment by a8568730** [comment]
結論：這用程式撈出來，莫叫 naphing 做粗工。
PR： #193 
NG稿做好矣
