### ISSUE TITLE
教典有收 現此時 hiān-tsú-sî

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#194]
詞目 | 現此時
-- | --
音讀 | hiān-tshú-sî　又唸作hiān-tsú-sî

2174 應該無 NG

https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=7613&curpage=1&sample=%E7%9B%AE%E5%89%8D&radiobutton=1&querytarget=2&limit=20&pagenum=1&rowcount=9

**Comment by naphing** [comment]
收著，已經改
