### ISSUE TITLE
3179 「磅」發音無夠清楚

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#210]
哼，這擺講話遮爾聳，你的橐袋仔內一定是袋磅子。
Hmh, tsit pái kóng-uē tsiah-nī sáng, lí ê lak-tē-á-lāi it-tīng sī tē pōng-tsí.

磅發音無夠清楚，像pok

**Comment by a8568730** [comment]
到時重錄。

**Comment by a8568730** [comment]
改做錄
哼，這擺講話遮爾聳，你的橐袋仔內一定是pha-lí-phá-lih。
