### ISSUE TITLE
2899 「率」音

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#214]
2899
佇十八號親率素還真
Tī tsa̍p-peh hō tshin-suài Sòo-huân-tsin

率suài音是否成立需討論，我佇揣台語查攏無這个音，敢會是受華語影響讀毋著？
lu̍t：效率、匯率 
sut：輕率、率先
https://chhoe.taigi.info/search?method=all-field&searchMethod=contains&value=%E7%8E%87

**Comment by a8568730** [comment]
彼工佇錄音室討論的結論：就當做收俗音。

**Comment by sih4sing5hong5** [comment]
Sîng-hông 才整理到hackmd

**Comment by sih4sing5hong5** [comment]
hackmd--ah
