### ISSUE TITLE
4/20 NG愛重錄的句

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#215]
3719
哼，這擺講話遮爾聳，你的橐袋仔內一定是袋磅子。
Hmh, tsit pái kóng-uē tsiah-nī sáng, lí ê lak-tē-á-lāi it-tīng sī tē pōng-tsí.
（磅字發音無清楚）

2723
咱拚命作穡，好空煞𪜶咧卯？
Lán piànn-miā tsoh-sit, hó-khang suah in teh báu?
（老師笑場，有剪正確版來補了嗎？）

**Comment by sih4sing5hong5** [comment]
多謝你鬥整理起來。 :)

**Comment by a8568730** [comment]
Apr 20, 2019/重錄/

3719 哼，這擺講話遮爾聳，你的橐袋仔內一定是pha-lí-phá-lih。
你錢著愛袋予好，毋通予人剪去。
你錢著愛袋予好，毋通予剪綹仔剪去。
2723 咱拚命作穡，好空煞𪜶咧卯？

**Comment by a8568730** [comment]
3719, 2723 已經共原本的音檔換做新的音檔

**Comment by a8568730** [comment]
賰的兩句已經開csv匯入去，`重錄_420`

**Comment by a8568730** [comment]
@naphing 發覺應該是3179，毋是3719？

**Comment by a8568730** [comment]
`重錄_420` 上線矣
