### ISSUE TITLE
合成文本連字符＆數字欲調整無

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#226]
1.合成文本的羅馬字一寡連字符毋著（若照教育部規則），需要調整無？
目前除了明顯輕聲有補--已外攏猶未改

2.數字，譬如月份日期人數等一寡數字原稿是拍數字。
我是改做羅馬字，若會影響音節統計啥我才閣改轉來

**Comment by sih4sing5hong5** [comment]
> 1.合成文本的羅馬字一寡連字符毋著（若照教育部規則），需要調整無？
> 目前除了明顯輕聲有補--已外攏猶未改
照教育部

> 
> 2.數字，譬如月份日期人數等一寡數字原稿是拍數字。
> 我是改做羅馬字，若會影響音節統計啥我才閣改轉來
漢字、羅馬字攏愛改，莫用阿拉伯數字

**Comment by naphing** [comment]
改好矣...對甲目睭挩窗

**Comment by sih4sing5hong5** [comment]
對好我就先close
