### ISSUE TITLE
修對齊失敗--ê

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#229]
https://媠聲服務.意傳.台灣/admin/SuiSiannAdminApp/%E5%8F%A5%E8%A1%A8/?o=-6.7.1

3180 3271

![2019-05-14 09-55-12 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/57665426-62d1ca80-762e-11e9-9334-6cc8328740e5.png)

**Comment by naphing** [comment]
隨來修，修好才閣回issue通知

**Comment by naphing** [comment]
1.確定補字音的已經處理好勢，請阿莉 @a8568730 更新用字表
2.幾字漢字寫法查無明確答案，先改寫做羅馬字。#230

**Comment by sih4sing5hong5** [comment]
Ho--ooh.

我leh準備訓練新模型，創結案報告
