### ISSUE TITLE
幾个漢字無法度確定

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#230]
一、
俗音，補入去用字表
2899：率suài（原底只有lu̍t/sut音）
佇十八號親率素還真
Tī tsa̍p-peh hō tshin-suài Sòo-huân-tsin, 

二、查過辭典，攏無明確寫法。我攏**先改做羅馬字**
1619：耗hàu
耗資數十萬、 這動員數千人。
Hàu tsu sòo tsa̍p-bān, tse tōng-uân sòo tshing lâng.

2728：縈înn
跋餅著準備，代先唱規矩。眾人聽分明，事後莫縈纏。
pua̍h-piánn tio̍h tsún-pī, tāi-sing tshiàng kui-kí. Tsìng-lâng thiann hun-bîng, sū-āu bo̍h înn-tînn.

3067、3068、3069：映iànn
光映映的店內啥物攏有咧賣，
Kng-iànn-iànn ê tiàm-lāi siánn-mi̍h lóng ū teh bē,

**Comment by sih4sing5hong5** [comment]
hackmd--ah
