### ISSUE TITLE
4943 「khè」程車

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#234]
老師第一次唸是「kè程車」，第二次唸成「khè程車」，後者收在教典「計程車」的又音，但是「計」單獨一字的時候沒有「khè」的音

**Comment by sih4sing5hong5** [comment]
教典ê又音就代表有合彼漢字
所以`khè-thîng-tshia`ê漢字有法度寫做`計程車`
孤字誠濟無收，這是一定愛漢字ê限制
