### ISSUE TITLE
5094 感情「好惟是hó-bî-sī」查不到意思

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#235]

**Comment by naphing** [comment]
是：[好唯是 hó-bî-sī](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=14046&curpage=1&sample=%E5%A5%BD%E5%94%AF&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=1)

5094 開頭的「尪」仔某打錯沒改到嘿
