### ISSUE TITLE
5131 「個個kô-kô」字典查無

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#236]

**Comment by naphing** [comment]
我也查不到，最多只有臺日大辭典裡有泉州音的[gê-gê](http://taigi.fhl.net/dict/search.php?DETAIL=1&LIMIT=id=67591&dbname=dic&graph=2)
@sih4sing5hong5 董娘有空回應一下彼時按怎標做kô-kô音
說不定是標錯了，然後老師就跟著念錯了XDDD

**Comment by niauah** [comment]
台文華文線頂辭典有XD
https://chhoe.taigi.info/TaibunHoabunSoanntengSutian/42744

**Comment by sih4sing5hong5** [comment]
愛看紙本稿

**Comment by naphing** [comment]
對允言老師的台語文語詞語料庫查到kô-kô只有兩句
Kô-kô tio̍h chhut lín pún-sū;（翻譯蒟蒻：個個著出恁本事）
愛一個工程師，報名--ê 就有五百幾個， kô-kô m̄ 是碩士就是大學出業，失業無工課做（這句...XD）





Kô-kô | tio̍h chhut lín pún-sū;
-- | --


Kô-kô | tio̍h chhut lín pún-sū;

**Comment by sih4sing5hong5** [comment]
按呢 `kô-kô` 是台語詞
chhoeTaigi ê `kô`攏無`個`ê用法，所以漢字部份嘛寫`kô-kô`
