### ISSUE TITLE
5264 翕相siòng/翕像siōng

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#237]
音檔讀hip-siōng ，應該是「像」
相siòng：相機siòng-ki、相片siòng-phìnn

**Comment by naphing** [comment]
教典：[翕相](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=8939&curpage=1&sample=hip&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=17)
hip-siòng　又唸作hip-siōng

**Comment by sih4sing5hong5** [comment]
所以naphing ê意思是不管是` hip-siòng`抑是`hip-siōng`，漢字攏寫`翕相`
