### ISSUE TITLE
357篇 地號名 鹽水kiâm-tsuí 

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#238]
這整篇都有的問題：
kiâm-tsuí 漢字打「鹽水」的話，自動產生的羅馬字應該會跑出 iâm-tsuí ，kiâm沒有對應到「鹽」

**Comment by naphing** [comment]
拍「鹹水」，地方口語攏叫遐做鹹水，
寫「鹽」是歷史書面紀錄誤寫做鹽，之後就沿用了
https://zh.wikipedia.org/wiki/%E9%B9%BD%E6%B0%B4%E5%8D%80

關於臺灣傳統地名的issue，可參考#107
