### ISSUE TITLE
5898 5900 完全無「siâng/siāng」

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#239]
老師兩次讀不一樣，我自己發音感覺是siâng，但稿上是寫siāng

**Comment by naphing** [comment]
兩个音攏有人讀
https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=5246&curpage=1&sample=siang5&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=3
