### ISSUE TITLE
6041 「刁工」

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#240]
老師讀 tiau-kang ，我感覺嘛會使，但是教典無收。

**Comment by niauah** [comment]
https://chhoe.taigi.info/search?method=basic&searchMethod=equals&spelling=tiau-kang&spellingMethod=kiplmj_unicode

**Comment by naphing** [comment]
教典：[刁工](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=81&curpage=1&sample=tiau-kang&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=1)
hiau-kang　又唸作tiau-kang
