### ISSUE TITLE
6064 「美妙biāu」

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#241]

**Comment by niauah** [comment]
妙 讀做 biāu 其他字典有，教典無 
https://chhoe.taigi.info/search?method=basic&searchMethod=equals&spellingMethod=kiplmj_unicode&taibun=%E5%A6%99

**Comment by naphing** [comment]
教典：[美妙](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=51061&curpage=1&sample=%E7%BE%8E%E5%A6%99&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=1)
bí-miāu　又唸作bí-biāu
