### ISSUE TITLE
6260 干焦...「爾niâ/niā」

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#242]
句尾的「爾」 教典只有收 niā，但是我自己實際發音是 niâ，不太確定是本來就有兩個讀音，還是niâ其實是niā-niā的合音？

**Comment by naphing** [comment]
niâ是合音，漢字部分就打羅馬字niâ，
爾爾niā-niā

參考先前的issue #101
