### ISSUE TITLE
「in」用羅馬字或漢字的問題

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#243]
文章的稿裡面是用羅馬字，我的電腦因為顯示不出來，所以校對的時候也都把原本自動辨識出來的漢字改掉了，這樣會不會影響到辨識的準確度？

**Comment by naphing** [comment]
問董娘 @sih4sing5hong5 
這非我能力所及XDDD

**Comment by sih4sing5hong5** [comment]
https://tauhu.tw/ 這thiap藥仔看有效--bô

**Comment by niauah** [comment]
我共chrome的自訂字型設定做Tauhu oo，就有法度顯示矣。本來是按算直接改Django網站的html，但是我改袂過來，可能是網站權限的問題？

**Comment by sih4sing5hong5** [comment]
所以這陣無問題--ah？

**Comment by niauah** [comment]
顯示ok
按呢進前共漢字𪜶改做羅馬字的敢愛閣改轉來？

**Comment by sih4sing5hong5** [comment]
先免，到時程式做伙處理
