### ISSUE TITLE
7250 均屬 kin-sio̍k 

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#245]
均屬 kin-sio̍k

干焦台日典有 
http://taigi.fhl.net/dict/search.php?graph=1&skey=kun-siok8

**Comment by sih4sing5hong5** [comment]
若別个辭典有漢字，而且用字攏tī教典ê規範內底(均 kin 屬sio̍k)，就用這漢字
