### ISSUE TITLE
7681 默 讀音

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#246]
查字典「默」是讀做 bi̍k，但是這規篇的稿佮老師唸的攏是bua̍t

**Comment by sih4sing5hong5** [comment]
白話字 | 教育部羅馬字 | 漢羅台文(白話字) | 漢羅台文解說(白話字) |  
-- | -- | -- | -- | --
boa̍t | bua̍t | [末] | (1)最後尾。 (2)景氣無好。



https://zh.wikipedia.org/wiki/%E5%AA%BD%E7%A5%96
```
媽祖原名林默（暱稱「默娘」），排行家中老么
```
敢有關係？

**Comment by sih4sing5hong5** [comment]
https://po3c.com/video/t65835.Y6Kay2

中教大應該是看這拍--ê ，12：10秒ê所在

**Comment by niauah** [comment]
但是若按呢解說就佮文章內底講的（恬靜＝默）袂合

**Comment by sih4sing5hong5** [comment]
咱這陣mái開時間處理這種漢字、漢字就照寫`Bua̍t娘`
