### ISSUE TITLE
7390 「妹妹」讀做 「me--meh」「 me-me」

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#247]
me--meh、me-me 應該是受華語影響的，毋是漢字「妹」原本的音。7386的「弟弟」也是。

在355出現很多次，我先用羅馬字標，定案之後再一起改。

**Comment by sih4sing5hong5** [comment]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/179#issuecomment-470419423
