### ISSUE TITLE
4936 規個月 要不要當同一個詞

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#248]
我自己感覺是 kó 和 gue̍h 分開比較合規則：量詞和名詞分寫
但 kui 和 kó 不知道該不該分開

**Comment by sih4sing5hong5** [comment]
@niauah  列出教典ê例予ta̍k-ke看~~

**Comment by niauah** [comment]
徙過Jiboo遐

**Comment by niauah** [comment]
例
一個月權領萬二箍。,Tsi̍t kò gue̍h khuân niá bān-jī khoo.
伊氣甲規个面膨起來。,I khì kah kui-ê bīn phòng--khí-lâi

**Comment by naphing** [comment]
Naphing見解
「規個月」連寫，有獨立語意，指個把月，不一定完整一個月。若數詞＋量詞＋名詞就會拆寫

**Comment by niauah** [comment]
我也覺得有獨立語意
那如果像「個外月」也是這樣嗎，還是比較接近「個外」（數詞）+「月」（名詞）

**Comment by niauah** [comment]
1738,1758,2386,1,伊規工攏失神失神。,I kui kang lóng sit-sîn-sit-sîn. ,他一整天都魂不守舍。
2812,2825,3814,1,你這隻米蟲，規工坐咧，攏毋去揣頭路。,"Lí tsit tsiah bí-thâng, kui kang tsē--leh, lóng m̄ khì tshuē thâu-lōo. ",你這隻米蟲，每天坐著，都不去找工作。
3729,3595,4925,1,毋去學一个工夫，規工坐佇遐，直直侗戇去。,"M̄ khì o̍h tsi̍t ê kang-hu, kui kang tsē tī hia, ti̍t-ti̍t tòng-gōng--khì. ",不去學個本事，整天坐在那兒，越來變得越笨。
5361,5130,7058,1,規工枵飽吵，強欲予你煩死！,"Kui kang iau-pá-tshá, kiōng-beh hōo lí huân--sí! ",整天無理取鬧，我都快被你煩死了！
6501,6177,8503,1,規工攏浸佇房間內。,Kui kang lóng tsìm tī pâng-king lāi. ,一整天都待在房間裡頭。
8329,8073,10976,1,無，你是咧陷眠是無？規工戇神戇神，叫攏袂應。,"Bô, lí sī teh hām-bîn sī--bô? Kui kang gōng-sîn-gōng-sîn, kiò lóng bē ìn. ",你是腦筋糊塗啦？整天呆呆傻傻的，叫你也不會回答。
8450,8250,11193,1,你規工按呢踅踅唸，敢袂喙焦？,"Lí kui kang án-ne se̍h-se̍h-liām, kám bē tshuì-ta? ",你整天這樣嘮叼不休，難道不會口渴嗎？
9231,9127,12286,1,做業務就是規工跑無停。,Tsò gia̍p-bū tō sī kui kang pháu bô thîng. ,當業務就是整天跑不停。
9583,9472,12744,1,伊規工攏咧想空想縫，毋知欲做啥物歹代誌。,"I kui kang lóng teh siūnn-khang-siūnn-phāng, m̄ tsai beh tsò siánn-mih pháinn tāi-tsì. ",他整天都在打鬼主意，不知道想做什麼壞事。
11221,11125,14895,1,你毋通規工憂頭苦面好無？,Lí m̄-thang kui kang iu-thâu-khóo-bīn hó--bô? ,你不要整天愁眉苦臉好嗎？
11806,11711,15667,1,為著生活，規工操勞。,"Uī-tio̍h sing-ua̍h, kui kang tshau-lô. ",為了生活，整天辛苦的作事。
12784,12677,16933,1,伊愛錢無惜性命，規工咧軁錢空。,"I ài tsînn bô sioh sènn-miā, kui kang teh nǹg-tsînn-khang. ",他愛錢不顧性命，成天在錢上鑽營。
12897,12792,17078,1,囡仔人毋通規工佇外口颺颺飛。,Gín-á-lâng m̄-thang kui kang tī guā-kháu iānn-iānn-pue. ,小孩子不要成天在外頭活躍，不知回家。
14088,13917,20678,0,伊力草真飽，工課做規工嘛袂忝。,"I la̍t-tsháu tsin pá, khang-khuè tsò kui-kang mā bē thiám. ",他精體力充沛，工作一整天也不累。
14612,14339,21221,1,宿題傷濟，禮拜日寫規工嘛寫袂了。,"Siok-tê siunn tsē, lé-pài-ji̍t siá kui-kang mā siá bē liáu. ",作業太多，星期日寫一整天也寫不完。
14613,14339,21221,2,伊規工攏佇外口拜訪客戶。,I kui-kang lóng tī guā-kháu pài-hóng kheh-hōo. ,他成天都在外面拜訪客戶。
14668,14382,21272,0,工課做規工，規身軀痛疼。,"Khang-khuè tsò kui-kang, kui-sin-khu thàng-thiànn. ",工作做了一整天，全身疼痛。
15005,14654,21603,0,伊規工攏佇厝裡無出去。,I kui-kang lóng tī tshù--lí bô tshut--khì. ,他整天都在家沒出門。

**Comment by naphing** [comment]
單獨「個外月」，連寫
加數詞一二三半...，「半個外月」全拆寫
kò-guā連寫奇怪，應該是數詞+外才連寫

**Comment by niauah** [comment]
會想到這個是因為 「百外个」應該是寫做 pah-guā ê
這裡的「個」又像數詞又像量詞，有點困惑XD

**Comment by sih4sing5hong5** [comment]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/110

**Comment by naphing** [comment]
> 會想到這個是因為 「百外个」應該是寫做 pah-guā ê
> 這裡的「個」又像數詞又像量詞，有點困惑XD

個是量詞，數詞是一二三、十百千萬、零、空

**Comment by niauah** [comment]
我想的是「個外（月）」和「十外」、「百外」的構詞方式很像
前面可以再加數詞--兩個外月、三百外箍
不加的時候就等於「一個」、「一百」

**Comment by naphing** [comment]
個是量詞，只接「月」，不太可能跟其他名詞結合。
十外、百外是不定量數詞，後面可以接一堆名詞。

**Comment by niauah** [comment]
懂了XD

**Comment by sih4sing5hong5** [comment]
上尾愛加結論~~

**Comment by niauah** [comment]
結論

> 單獨「個外月」，連寫
> 加數詞一二三半...，「半個外月」全拆寫
> 數詞+外才連寫

**Comment by sih4sing5hong5** [comment]
先按呢，等 #259 做伙問
