### ISSUE TITLE
4961 「考前」敢有合「名詞+方位詞」的結構？

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#249]
像「山頂」、「門口」著算是一個詞

**Comment by niauah** [comment]
徙過Jiboo

**Comment by naphing** [comment]
考前，是「考試進前」，毋是獨立的詞，拆寫

**Comment by sih4sing5hong5** [comment]
> 考前，是「考試進前」，毋是獨立的詞，拆寫

敢是拍毋著？

`獨立`才拆寫
`毋是獨立`愛合寫

**Comment by niauah** [comment]
Naphing的意思應該是 「考前」毋是to̍k-li̍p的詞 所以拆寫？

**Comment by naphing** [comment]
> Naphing的意思應該是 「考前」毋是to̍k-li̍p的詞 所以拆寫？

YAP
考前算詞組，考試N＋進前Adv.
