### ISSUE TITLE
教典「有的」斷詞規則混亂

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#250]
2192,2144,2953,1,有的人逐擺感冒攏愛吊大筒。,Ū ê lâng ta̍k pái kám-mōo lóng ài tiàu tuā-tâng. 
3615,3472,4765,1,有的歌手自細漢就四界去走唱。,Ū ê kua-tshiú tsū sè-hàn tō sì-kè khì tsáu-tshiùnn. 
6770,6532,8961,1,有的學校會教學生紡紗。,Ū-ê ha̍k-hāu ē kà ha̍k-sing pháng-se. ,
7259,7068,9633,1,有的生理人做生理會唬秤頭，所以買物件愛注意。,"Ū-ê sing-lí-lâng tsò-sing-lí ē hóo-tshìn-thâu, sóo-í bé mi̍h-kiānn ài tsù-ì. ",
10104,9948,13397,1,有的樹仔毋免落肥。,Ū-ê tshiū-á m̄-bián lo̍h-puî. ,
11320,11237,15044,1,有的人食麻油了後會感覺較熱。,Ū ê lâng tsia̍h muâ-iû liáu-āu ē kám-kak khah jia̍t. ,
13984,13790,20533,1,較早的計程車，有的較無愛載短站的人客。,"Khah-tsá ê kè-thîng-tshia, ū-ê khah bô ài tsài té-tsām ê lâng-kheh. "
14065,13896,20653,1,有的人誠厚譴損，做啥物代誌攏著閣看日。,"Ū-ê lâng tsiânn kāu-khiàn-sńg, tsò siánn-mih tāi-tsì lóng tio̍h koh khuànn-ji̍t. ",
14775,14463,21381,2,尾牙有的公司辦桌請員工，攏愛倩𠢕詼諧的歌星來鬥鬧熱。,"Bué-gê ū-ê kong-si pān-toh thiánn uân-kang, lóng ài tshiànn gâu khue-hâi ê kua-tshenn lâi tàu-lāu-jia̍t. "
14818,14503,21425,0,囡仔墜腸，有的家己會好去，大部份攏愛去開刀治療。,"Gín-á tuī-tiông, ū-ê ka-kī ē hó--khì, tuā-pōo-hūn lóng ài khì khui-to tī-liâu. ",

**Comment by sih4sing5hong5** [comment]
寄ê內容kah回應才貼起來~~

**Comment by niauah** [comment]
回批

>陳先生：您好
您於108年6月14日致本部部長信箱信件，我們已經收到了，謝謝您的來信。有關您來信詢問《臺灣閩南語常用詞辭典》（以下簡稱本典）部分例句中「有的」音讀應連寫或分寫一事，向您說明如下：
有關本典「有的」義項為「一些」時，視為一個詞，應連寫為「ū-ê」，例句將全面檢視調整。
感謝您來信提醒，未來仍請您持續支持，亦請不吝賜教。

**Comment by niauah** [comment]
結論應該是愛連做伙

**Comment by sih4sing5hong5** [comment]
若無問題就close~

**Comment by sih4sing5hong5** [comment]
因為教典會更新，就無另外加入去hackmd內底--ah
