### ISSUE TITLE
5109 「守寡」讀音

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#251]
音檔內若像是讀 tsiú-kuánn ，我聽著無啥確定

臺日典收 siú-kuánn、 tsiú-kuánn 
教典收 tsiú-kuá、tsiúnn-kuánn

**Comment by naphing** [comment]
@niauah 
老師念kuánn 成立
記得去網站修正

**Comment by niauah** [comment]
修好
