### ISSUE TITLE
「厝裡」、「庄裡」這類用法的標音

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#255]
秀容老師發音習慣是 --lín （我自己發音也偏這個），教典只有收 tshù--lí/tshù--nih，我現在暫時都照教典標 --lí

**Comment by sih4sing5hong5** [comment]
羅馬字照發音標`--lín`，
TJ有寫是仝源頭，所以漢字照教典寫`裡`

![掃描的文件1](https://user-images.githubusercontent.com/5996555/59496882-f5cb8200-8ec4-11e9-922a-84447794ab78.jpg)
![掃描的文件2](https://user-images.githubusercontent.com/5996555/59496883-f5cb8200-8ec4-11e9-8756-06ce10ff189d.jpg)

**Comment by sih4sing5hong5** [comment]
hackmd--ah
