### ISSUE TITLE
355篇 「弘毅」人名規篇攏唸毋著

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#263]
「毅」字典是寫 gē/gī 無ik的音
我是感覺會當共攏總擲掉，較袂汙染著資料，橫直是教典無收mā罕得用的字。

**Comment by sih4sing5hong5** [comment]
揣一ê有`ik`ê漢字、人會提來號名--ê，來kā換掉

**Comment by naphing** [comment]
嘛會使改漢字符合讀音，人名較無要緊，看董娘意思如何

**Comment by naphing** [comment]
董娘幹嘛搶先我！

**Comment by sih4sing5hong5** [comment]
> 董娘幹嘛搶先我！

緊你8秒
![2019-06-19 17-03-42 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/59752077-3dcb1a00-92b4-11e9-9404-ed47d9ba6b10.png)

**Comment by niauah** [comment]
好，就按呢XDD
(到今效率上懸的issue
