### ISSUE TITLE
7910 Hong-si

### ISSUE THREAD

**Issue by niauah** [Sui-Siann-Dataset/Sui-Siann-Dataset#266]
hong-si 查無意思，老師嘛無確定按怎唸
文稿寫的 hong-sî 嘛查無

**Comment by niauah** [comment]
hong-si 查無意思，老師嘛無確定按怎唸
文稿寫的 hong-sî 嘛查無

**Comment by naphing** [comment]
敢會是落字?  減拍n, 可能是hong-sîn? 風神

**Comment by sih4sing5hong5** [comment]
![2019-06-24 13-37-47 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/59994113-455c3b80-9685-11e9-9e9a-38715bd5ce2c.png)

**Comment by naphing** [comment]
「風絲」與稿子前後文不搭

**Comment by sih4sing5hong5** [comment]
> 「風絲」與稿子前後文不搭

若看彼句嘛是袂順，彼句就莫ti̍h。

**Comment by niauah** [comment]
好，我擲hìnn-sak
