### ISSUE TITLE
豆號 kā 一句話斷做兩句。

### ISSUE THREAD

**Issue by a8568730** [Sui-Siann-Dataset/Sui-Siann-Dataset#33]
#### Oct 6, 2018_48.wav 
發現 huat-hiān 的 hiān 是有變調的。
```
...Pew研究中心調查發現，九十三pha的美國人認為，
Tsuè-kīn Bí-kok tú-hó ū tsi̍t-kuá sin ê gián-kiù. 
Pew gián-kiù tiong-sim tiau-tsa huat-hiān, káu-tsa̍p-sann pha ê Bí-kok-lâng jīn-uî, 
```

#### Oct 6, 2018_59.wav
```
Tufekci指出，社交媒體等...
Tufekci kí-tshut, Siā-kau muî-thé tíng...
```

**Comment by a8568730** [comment]
Oct 6, 2018_92.wav
有一對已經結婚十冬的翁仔某宣佈。
ū tsi̍t tuì í-king kiat-hun tsa̍p tang ê ang-á-bóo suan-pòo.

Oct 6, 2018_93.wav
有一對已經結婚十冬的翁仔某宣佈，若是國會通過...
ū tsi̍t tuì í-king kiat-hun tsa̍p tang ê ang-á-bóo suan-pòo, nā-sī kok-huē thong-kuè...

**Comment by sih4sing5hong5** [comment]
結論：

若是有變調，後壁ài是豆號抑是冒號

**Comment by sih4sing5hong5** [comment]
整理過--ah

**Comment by sih4sing5hong5** [comment]
確定一下ta̍k-ke敢有看--著

**Comment by naphing** [comment]
> 確定一下ta̍k-ke敢有看--著

Naphing got it

**Comment by sih4sing5hong5** [comment]
整理過--ah
