### ISSUE TITLE
多音節動詞 + 著，愛分寫

### ISSUE THREAD

**Issue by a8568730** [Sui-Siann-Dataset/Sui-Siann-Dataset#34]
./角花仔佮素花仔_hanlo.odt.csv:"Oct 20, 2018 _16.wav",「對不住啦！我毋知佗落得失著你乎(honnh) ……？」素花仔誠細膩按呢ka應。,"""Tuì-put-tsū--lah! Guá m̄-tsai tó lo̍h **tik-sit tio̍h** lí--honnh...?"" sòo-hue-á tsiânn sè-jī án-ne ka ìn.",,

./角花仔佮素花仔_hanlo.odt.csv:"Oct 20, 2018 _17.wav",「嘿(heh)！你來到這搭(tah)，就是得失著我矣，好啊！莫囉唆、我無想欲佮你答喙鼓……。」角花仔講煞，隨越頭做伊摔(siak)大眠矣。,"""Heh! Lí lâi-kàu tsit-tah, tō-sī **tik-sit tio̍h** guá--ah, hó--ah! Mài lô-so, guá bô siūnn beh kah lí tap-tshuì-kóo... "" Kak-hue-á kóng-suah, suî ua̍t-thâu tsò i siak-tuā-bîn--ah.",,

./賣圓仔的神仙_hanlo.odt.csv:"Oct 20, 2018 _103.wav",漢鍾離聽著的對話，心內想講：「抑是有人注意著彼粒山矣，我掠準講這陣人干焦知影通食爾咧！」,"Hàn Tsing-lî thiann-tio̍h ê tuì-uē, sim-lāi siūnn-kóng: ""Ia̍h-sī ū lâng **tsù-ì tio̍h** hit lia̍p suann--ah, guá lia̍h-tsún-kóng tsit tīn lâng kan-na tsai-thang thang tsia̍h nia̋--leh!""",,

**Comment by sih4sing5hong5** [comment]
@a8568730 上尾是？

**Comment by naphing** [comment]
> @a8568730 上尾是？

分寫？我在教典都查不到「兩音節以上的V+著」的寫法，懷疑是食著華語喙瀾

**Comment by sih4sing5hong5** [comment]
伊講分寫~

**Comment by sih4sing5hong5** [comment]
hackmd--ah
