### ISSUE TITLE
 為啥物uī siánn-mi̍h改uī-siánn-mi̍h 

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#41]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Tsit-Tshing/issues/49

**Comment by a8568730** [comment]
確定愛寫uī-siánn-mih。

蔡小姐：您好
　　您於107年11月1日致本部部長信箱信件，我們已經收到了，謝謝您的來信。有關您來信詢問《臺灣閩南語常用詞辭典》（以下簡稱本典）「為啥物」一詞是否需連字符一事，向您說明如下：
有關本典「為啥物」一詞於「為」詞目的例句中呈現分寫，經查屬誤植，應為連寫，業已修正。
感謝您來信提醒，未來仍請您持續支持，亦請不吝賜教。敬祝。
平安健康、萬事如意！
　　教育部　敬上

**Comment by sih4sing5hong5** [comment]
hackmd--ah
