### ISSUE TITLE
英語詞標記

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#45]
漢字部份ê英語，攏照漢字部份ê羅馬字寫法

```
漢：B-two  羅：B-two
漢字： B三 臺羅：B-sann
C++：漢字＆臺羅：C-plus-plus
符號類：+ ->plus &->and(,B&Q)
R&B：R-and-B
Uber(合念)
U-bike(U分念)
```

https://hackmd.io/wjDAlKVcT0yuoT-y5jlFxg?view#20190109%E9%96%8B%E6%9C%83

**Comment by sih4sing5hong5** [comment]
查LJ Speech `FBI`, `PRS`
LJ050-0179|Based on its experience during this period, the Secret Service now recommends that additional personnel be made available to PRS|Based on its experience during this period, the Secret Service now recommends that additional personnel be made available to PRS
LJ050-0208|salaries are below those of the FBI and leading municipal police forces.|salaries are below those of the FBI and leading municipal police forces.
LJ050-0209|The assistant to the Director of the FBI testified that|The assistant to the Director of the FBI testified that

**Comment by naphing** [comment]
2B：漢字二B；臺羅ㄦˋ-B
柯P：漢字柯P；臺羅ㄎㄜ-P

> 漢字部份ê英語，攏照漢字部份ê羅馬字寫法
> 
> ```
> 漢：B-two  羅：B-two
> 漢字： B三 臺羅：B-sann
> C++：漢字＆臺羅：C-plus-plus
> 符號類：+ ->plus &->and(,B&Q)
> R&B：R-and-B
> Uber(合念)
> U-bike(U分念)
> ```
> https://hackmd.io/wjDAlKVcT0yuoT-y5jlFxg?view#20190109%E9%96%8B%E6%9C%83

**Comment by sih4sing5hong5** [comment]
整理過--ah

**Comment by sih4sing5hong5** [comment]
照全羅書寫，規ê當做外語詞`Lí kám ū 二B ê iân-pit?`
