### ISSUE TITLE
 符號Lá-sih標記 

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#47]
https://github.com/Sui-Siann-Dataset/Sui-Siann-Tsit-Tshing/issues/66
回應#7狀況
類似破折號，全形 —
參考張裕宏「白話字基本論」冊P114
![26159](https://user-images.githubusercontent.com/35830498/50953634-fb283900-14ee-11e9-9933-1ca349fd51d8.jpg)

**Comment by sih4sing5hong5** [comment]
@a8568730 @naphing
書寫khǹg `Sui-Siann-Dataset`專案
語句補充khǹg `Sui-Siann-Tsit-Tshing`專案

按呢好--bô？

**Comment by sih4sing5hong5** [comment]
教典用兩ê`——`，咱就照教典？

序號 | 詞目 | 音讀 | 附錄
-- | -- | -- | --
1 | 缺喙的食米粉——看現現。 | Khih-tshuì--ê tsia̍h bí-hún——khuànn-hiān-hiān. | 附錄
2 | 大甲溪放草魚——有準無。 | Tāi-kah-khe pàng tsháu-hî——ū tsún bô. | 附錄

**Comment by sih4sing5hong5** [comment]
毋過 #7 ê 例是
```
Oct 8, 2018 _270.wav
「好、好、好啦！阿妙乖－咱就買這軀好啦！莫吼乎(honnh)，乖──」。
"Hó, hó, hó--lah! A-biāu kuai － lán tō bé tsit su hó--lah! Mài háu--honnh, kuai ─ ─ ".
```
意思koh無sánn kâng

**Comment by sih4sing5hong5** [comment]
所以咱就照《重訂標點符號手冊》修訂版--破折號 用 `──` ？

**Comment by sih4sing5hong5** [comment]
@a8568730 @naphing 來--iooh，好食ê燒番麥~~

**Comment by a8568730** [comment]
> 來--iooh，好食ê燒番麥~~

了解，就是愛寫做兩个破折號
Lâi--iooh, hó-tsia̍h ê sio-huan-be̍h──

**Comment by naphing** [comment]
> @a8568730 @naphing 來--iooh，好食ê燒番麥~~

@sih4sing5hong5 上面在幹嘛=="
破折號是「全形」，不過我只能靠用微軟注音輸入法開符號表按出「—」，請幫我確認是不是這個？一堆橫線長一點短一點全形半形難分辨

**Comment by sih4sing5hong5** [comment]
> > @a8568730 @naphing 來--iooh，好食ê燒番麥~~
> 
> @sih4sing5hong5 上面在幹嘛=="
> 破折號是「全形」，不過我只能靠用微軟注音輸入法開符號表按出「—」，請幫我確認是不是這個？一堆橫線長一點短一點全形半形難分辨

毋是，你用ctrl+F 就會知有kâng無。按呢你對in 網頁 khok-pì就好--ah，較單純。

**Comment by naphing** [comment]
OK，以後直接COPY教育部標點符號手冊

**Comment by sih4sing5hong5** [comment]
我先開--開，等整理到 hackmd

**Comment by sih4sing5hong5** [comment]
hackmd--ah
