### ISSUE TITLE
合音詞「予人」

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#49]
hông標五調

**Comment by sih4sing5hong5** [comment]
整理過--ah

**Comment by sih4sing5hong5** [comment]
無記著為sannh選第5調
敢是因為口語調有第7調kah第3調？

**Comment by sih4sing5hong5** [comment]
> 無記著為sannh選第5調
> 敢是因為口語調有第7調kah第3調？

@naphing ~

**Comment by sih4sing5hong5** [comment]
Kah #80 敢會衝突？

**Comment by sih4sing5hong5** [comment]
所以口語調可能有3, 7, 5, 9調？

**Comment by naphing** [comment]
> 所以口語調可能有3, 7, 5, 9調？

@sih4sing5hong5 是，我攏聽過

**Comment by sih4sing5hong5** [comment]
先確定合音前，到底有變調無？
1. I hōo lâng phah.
2. I hōo lâng# phah.

**Comment by sih4sing5hong5** [comment]
> > 先確定合音前，到底有變調無？
> > 
> > 1. I hōo lâng phah.
> > 2. I hōo lâng# phah.
> 
> 兩句都成立，1單純陳述事實，hoo7跟lang5都變調，被打；2強調被「人」打，lang5維持本調
> 合音的狀況應該是指1

我落勾另外一種
3. I hōo--lâng phah.

@naphing 1, 3你是指tó一ê？

**Comment by sih4sing5hong5** [comment]
> > > 先確定合音前，到底有變調無？
> > > 
> > > 1. I hōo lâng phah.
> > > 2. I hōo lâng# phah.
> > 
> > 
> > 兩句都成立，1單純陳述事實，hoo7跟lang5都變調，被打；2強調被「人」打，lang5維持本調
> > 合音的狀況應該是指1
> 
> 我落勾另外一種
> 3. I hōo--lâng phah.

@naphing：  3 無合法

**Comment by sih4sing5hong5** [comment]
因為`予人`來源有`1. I hōo lâng phah.`佮 `2. I hōo lâng# phah.`兩種，
所以無法度照 #80 來知影有變調無，才有這个討論。

閣因為合音口語有 3,5,7,9 調，
`予人`合音用`變調`會有揣本調的困難，所以`予人`合音直接當作`本調`。

### 結論
第3調就標第3調。
第5調就標第5調。
第7調就標第7調。
第9調就標第9調。

**Comment by sih4sing5hong5** [comment]
hoo7  N # V.
hoo7 lang # V
hoo7 gua/li/i/gun/lin/in V
hoo7 lang V

**Comment by sih4sing5hong5** [comment]
hackmd--ah
#93
