### ISSUE TITLE
「遮的」臺羅三款標記

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#51]
教典詞條聲調寫tsia--ê
根據句子語意判斷，臺羅愛分三種標法
1.tsia--ê
輕聲，這些，屬代名詞
Tsia--ê guá lóng beh the̍h--khì.

2.tsia-ê
變7調，這些，屬指示形容詞，修飾後方N
Tsia-ê kué-tsí hōo lí tsia̍h.

3.tsia ê
tsia本調，這裡，屬指示形容詞，修飾後方N

**Comment by sih4sing5hong5** [comment]
hackmd--ah
