### ISSUE TITLE
漢字「趨 / 跙」 

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#55]
教典來源
趨tshu：1.形容詞，斜斜的 2.動詞，滑雪之類，趨雪
跙tshū：1.動詞：滑倒 2.動詞：上至下的滑動，跙流籠，跙冰

我覺得趨雪跟跙冰這兩個有問題，待我查查
但校對句都是「人滑倒」意思，用字跟臺羅都修正成「跙tshū」

**Comment by naphing** [comment]
ID 230、809

**Comment by naphing** [comment]
> 教典來源
> 趨tshu：1.形容詞，斜斜的 2.動詞，滑雪之類，趨雪
> 跙tshū：1.動詞：滑倒 2.動詞：上至下的滑動，跙流籠，跙冰
> 
> 我覺得趨雪跟跙冰這兩個有問題，待我查查
> 但校對句都是「人滑倒」意思，用字跟臺羅都修正成「跙tshū」

「趨tshu、跙tshū」按怎分？
承賢回應
根據台日，「tshū」干焦『滑行』（動詞）一个意思，其他的意思攏是講「tshu」。
毋過咧，因為走音+方言差，這馬「tshu」、「tsū」、「tshū」真oh分，看隨人的用法，隨个所在的區別、有分、按怎分、無分，逐款情形都有，攏無相仝。

所以我照音檔聲調來推斷用趨tshu或跙tshū

**Comment by sih4sing5hong5** [comment]
> 所以我照音檔聲調來推斷用趨tshu或跙tshū
好

**Comment by a8568730** [comment]
好

**Comment by sih4sing5hong5** [comment]
hackmd--ah
