### ISSUE TITLE
起去khí-lì的書寫方法

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#66]
khi2-li3寫做漢字是
起去？抑是 起來去 的合音詞？
我知影有li3這个講法，但是無確定伊漢字是？

承賢回答
khí--lih / khí--lì就是khí--khì（起去）的輕聲變調加上音韻OCP (Obligatory Contour Principle) 原則運作，阻止兩音節使用相同子音(kh)的結果，要寫漢字，也只好寫「起去」了。

**Comment by a8568730** [comment]
才閣麻煩加標仔~

**Comment by naphing** [comment]
我按存了才發現沒加，哪裡補？

**Comment by sih4sing5hong5** [comment]
![default](https://user-images.githubusercontent.com/5996555/51362174-7ac89000-1b0d-11e9-9e6d-03532abc7468.png)

**Comment by naphing** [comment]
我無齒輪通揤（眼神死）
![image](https://user-images.githubusercontent.com/35830498/51362345-21ad2c00-1b0e-11e9-84e9-3ce486157371.png)

**Comment by a8568730** [comment]
> khi2-li3寫做漢字是
> 起去？抑是 起來去 的合音詞？
> 我知影有li3這个講法，但是無確定伊漢字是？

TJ 共 khí-lì 收佇「起去」。
![image](https://user-images.githubusercontent.com/6355592/51363094-769e7180-1b11-11e9-9ade-1812910aeea6.png)

起來去
![image](https://user-images.githubusercontent.com/6355592/51363207-f3c9e680-1b11-11e9-9150-30990fd53630.png)
![image](https://user-images.githubusercontent.com/6355592/51363284-473c3480-1b12-11e9-975c-32d58da2202a.png)

**Comment by sih4sing5hong5** [comment]
@a8568730

**Comment by a8568730** [comment]
Kín khí-lí khuànn-māi，khí-lí口語調是一般變調

**Comment by naphing** [comment]
張裕宏辭典收li2又收li3，到底要li2還是li3！

**Comment by sih4sing5hong5** [comment]
> 更新例
> 
>     1. `Peh khí-lí khuànn-māi`，`khí-lí`口語調是 `1,1`
> 
>     2. `Peh--khí-lí`，`khí-lí`口語調是`輕聲,輕聲`
> 
>     3. `Peh bē khì--lí`，`khí-lí`口語調是`3,輕聲`

@naphing, @a8568730 先確定ta̍k-ke口語調是按怎，咱才來討論書寫

**Comment by a8568730** [comment]
更新例
>1. `Peh khí-lí khuànn-māi`，`khí-lí`口語調是 `1,1`

著

>2. `Peh--khí-lí`，`khí-lí`口語調是`輕聲,輕聲`

著

>3. `Peh bē khì--lí`，`khí-lí`口語調是`3,輕聲`

著

--
毋過針對3.，教典例句是按呢：
./例句.csv:1002,936,1298,1,我手尾力無夠，**捾袂起來**。
Guá tshiú-bué-la̍t bô-kàu, **kuānn bē khí--lâi.**
./例句.csv:9261,9156,12324,1,人講跋筊蓋毋好，是按怎你就是**改袂起來**？
Lâng kóng pua̍h-kiáu kài m̄ hó, sī án-tsuánn lí tō sī **kái bē khí--lâi**?

**Comment by a8568730** [comment]
我面頂直接共TJ的字拍拍出來矣。

> TJ 共 khí-lì 收佇「起去」。
khí-khì（ 
\> khit2-khì > khit2-lì > khí-lì > khí-lí > khí;  
\> khit2-khì > khit-khì > khit-lì > khih-lì > khì-lì > khí-lí > khí;  
\> khí-.khì > khit2-.khì >  khit-.khì > khit-.lì; 
\> khí-.khì > khí-.lì > khit2-.lì > khit-.lì; 
\> .khí-.khì > .khit-.khì > .khit-.lì; 
\> .khí-.khì > .khí-.lì > .khit-.lì）

**Comment by sih4sing5hong5** [comment]
@a8568730 有bat整理過[X去 X來](https://github.com/i3thuan5/khin1siann1-hun1sik4/blob/master/%E8%BC%95%E8%81%B2%E8%A9%9E%E8%B3%87%E6%96%99/%E5%85%A8%E9%83%A8%E8%BC%95%E8%81%B2%E8%A9%9E.csv#L37)
我整理一下

**Comment by sih4sing5hong5** [comment]
>     1. `Peh khí-lí khuànn-māi`，`khí-lí`口語調是 `1,1`
>     2. `Peh--khí-lí`，`khí-lí`口語調是`輕聲,輕聲`
>     3. `Peh bē khì--lí`，`khí-lí`口語調是`3,輕聲`
對`li`來講，第1調ē-tàng用再變調解說，所以本調寫sánn調攏合理，按呢咱配合教育部ê`khì`寫第3調，咱嘛寫第3調`lì`。
對`khi`來講，第1調嘛用再變調解說，所以本調寫3調較合理。

> 針對3.，教典例句是按呢：
> ./例句.csv:1002,936,1298,1,我手尾力無夠，捾袂起來。
> Guá tshiú-bué-la̍t bô-kàu, kuānn bē khí--lâi.

是講 @a8568730 有講著別个例
我tshuē面頂1~12項可能有相關ê詞

@naphing 你看你ê語感是？（面頂1~12項）
Tī `Peh A-B khuànn-māi`，A-B口語調一定愛唸 `1,1`--ê，是tó幾ê？
Tī `Peh A-B khuànn-māi`，A-B口語調ē-sái唸 `1,1`，嘛ē-sái唸一般變調--ê，是tó幾ê？
Tī `Peh A-B khuànn-māi`，A-B口語調一定照一般變調--ê，是tó幾ê？

**Comment by sih4sing5hong5** [comment]
以 https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/66#issuecomment-457081812 寫法為主

**Comment by sih4sing5hong5** [comment]
#93 
hackmd--ah

**Comment by naphing** [comment]
> 1. `Peh khí-lì khuànn-māi`，`khí-lì`口語調是 `1,1`
> 2. `Peh--khí-lì`，`khí-lì`口語調是`輕聲,輕聲`
> 3. `V ē/bē/ū/bô khí--lì`
> 
> * 照唸ê標
>   - a. `Peh bē khí--lì`，`khí-lì`口語調是`2,輕聲`
>   - b. `Peh bē khì--lì`，`khì-lì`口語調是`3,輕聲`
> 
> #### 結論
> 1, 2, 3-a `khí--lì`
> 3-b `khì--lì`
> 

狀況1，口語1,1是標khi2--li3?

**Comment by sih4sing5hong5** [comment]
> 狀況1，口語1,1是標khi2--li3?

是，標`khi2--li3`，順紲標`補語攏唸1調`ê狀況。

因為 #105 表示有這種情形ê補語袂少，可能koh會拄著別个

**Comment by a8568730** [comment]
> 以 [#66 (comment)](https://github.com/Sui-Siann-Dataset/Sui-Siann-Dataset/issues/66#issuecomment-457081812) 寫法為主
> 
> 1. `Peh khí-lì khuànn-māi`，`khí-lì`口語調是 `1,1`
> 2. `Peh--khí-lì`，`khí-lì`口語調是`輕聲,輕聲`
> 3. `V ē/bē/ū/bô khí--lì`
> 
> * 照唸ê標
>   - a. `Peh bē khí--lì`，`khí-lì`口語調是`2,輕聲`
>   - b. `Peh bē khì--lì`，`khì-lì`口語調是`3,輕聲`
> 
> #### 結論
> 1, 2, 3-a `khí--lì`
> 3-b `khì--lì`

結論的連字符小可寫毋著，1, 2, 3-a 毋是輕聲，猶原孤一个連字符。
1 寫做`khí-lí`
2 寫做`--khí-lì`
3-a 寫做`khí--lì`
3-b `khì--lì`
> 
> 漢字攏`起去`
> 
> #### 理由
> * 對`khí`來講，第1調用一般變調解說，所以本調寫2調較合理。
> * 對`lì`來講，第1調ē-tàng用再變調解說，所以本調寫sánn調攏合理，按呢咱配合教育部ê khì寫第3調，咱嘛寫第3調`lì`。
> * 無法度確定3-b著抑毋著，若有就先照結論標

**Comment by a8568730** [comment]
> > 狀況1，口語1,1是標khi2--li3?
> 
> 是，標`khi2--li3`，順紲標`補語攏唸1調`ê狀況。

狀況1是標`khi2-li3`，無輕聲的喔！

> 
> 因為 #105 表示有這種情形ê補語袂少，可能koh會拄著別个

**Comment by sih4sing5hong5** [comment]
hackmd照討論更新--ah
