### ISSUE TITLE
有「fiu」

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#75]
124 這齣電影的菜脯誠gâu搬，看了誠有fiu。
fiu敢有正式寫法？查！

**Comment by sih4sing5hong5** [comment]
拍`fu`，因為`nuance`唸`niu-ang-s`

https://www.merriam-webster.com/dictionary/nuance

**Comment by naphing** [comment]
收著，已經修改
