### ISSUE TITLE
臺羅顯示欄位寬度

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#76]
臺羅欄位敢有可能閣加闊？如果後壁匯入來的句袂親像承賢的按呢躼躼長，應該無需要改。若無，臺羅傷長敢若無啥方便看講>"<
![image](https://user-images.githubusercontent.com/35830498/51424861-bc8d2f80-1c0e-11e9-8bf9-a3d2225506f1.png)

**Comment by sih4sing5hong5** [comment]
這是程式問題~

**Comment by naphing** [comment]
> 這是程式問題~

歹勢，我有分類障礙

**Comment by sih4sing5hong5** [comment]
PR 上線矣。
