### ISSUE TITLE
合音標記規則

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#80]
1.口語九調，維持免改

2.根據原本的詞佇句內尾字敢會變調來決定合音詞的口語是毋是變調
如：毋好好仔拍拚趁錢，以後nài綴人會著？
假設kâng詞組行為會仝款。因為ná ē會變調，所以認為口語第2調嘛是經過變調，書寫寫第3調nài

3.拍無去/拍毋見 合音
拍無去phah-bô--khì　合音寫pháng--khì（因為去輕聲，前者維持本調）
拍毋見phah-m̄-kìnn　合音寫phàng-kìnn（3變2規則）

**Comment by sih4sing5hong5** [comment]
hackmd--ah

**Comment by a8568730** [comment]
>2.根據原本的詞佇句內尾字敢會變調來決定合音詞的口語是毋是變調
如：毋好好仔拍拚趁錢，以後nài綴人會著？
假設kâng詞組行為會仝款。因為ná ē的ē會變調，所以認為口語第2調嘛是經過變調，書寫寫第3調nài

我認為 nài 的語源是nà ē。

詞目 | 哪未
-- | --
音讀 | ná buē/ná bē　又唸作nà-buē/nà-bē
