### ISSUE TITLE
數字免用連字符的情形

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#81]
免寫的有
1.數字+量詞
兩三工nn̄g sann kang、三兩句sann nn̄g kù、五六个gōo la̍k ê

2.物件的型號、年份、電話號、信用卡號碼（以文讀音）唸的
X-box三六空：sam lo̍k khòng
二空一空年：jī khòng it khòng nî
空八空空，空九二，空空空：khòng pat khòng khòng

**Comment by sih4sing5hong5** [comment]
hackmd--ah
