### ISSUE TITLE
洪錦田角花仔的「益」音確認

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#88]
「真平」網站的用字版，**益**字音待確認，秀容老師口語調ia3，本調可能iah8或ia7

894
**益**角花仔煞變甲足目頭懸，臭煬塊塊，攏無癮佮遐舊厝邊相借問。

920
**益**角花仔看一下，暢甲掠袂牢，佇想講：「哇！這聲予我創一下有夠媠氣的，這步用了袂bái，此去阿妙就干焦佮意我一个啦呼！哈、哈、哈……」。

930
**益**角花仔佮素花仔，兩个一下相對看，煞規面笑吻吻的花蕊，一蕊一蕊一直浮出來……。

**Comment by a8568730** [comment]
Ē-tsái-á 問矣～

**Comment by a8568730** [comment]
洪老師回批：
```
汝是講[益],唸iah,同阿(ah),語助詞;陳三五娘內底个[益春],讀iah-tshun....
```

**Comment by naphing** [comment]
洪老師的解釋是「益」等同於前綴「阿」？「益春」是人名，
但因為歌仔冊用字非常多元/亂，建議「益」字直接，聽音檔反推本調標記可否？

參考
[廖瓊枝歌仔戲 陳三五娘 - 益春留傘](https://www.youtube.com/watch?v=VU-v58rmpj0) ) 0:50處
[葉青歌仔戲 陳三五娘 - 益春留傘](https://youtu.be/huWnko65OlA) 2:00處

**Comment by a8568730** [comment]
youtube 的網址 ē-tàng 共秒數嘛囥起去。
https://youtu.be/huWnko65OlA?t=119

**Comment by a8568730** [comment]
![youtube](https://user-images.githubusercontent.com/6355592/51654033-fa080900-1fd0-11e9-8c67-dd17167b2391.png)

**Comment by sih4sing5hong5** [comment]
> 洪老師回批：
> 
> ```
> 汝是講[益],唸iah,同阿(ah),語助詞;陳三五娘內底个[益春],讀iah-tshun....
> 孤一字,本調;佮一般仝款
> ```
洪老師應該是講`啊`



> 洪老師的解釋是「益」等同於前綴「阿」？「益春」是人名，
> 但因為歌仔冊用字非常多元/亂，建議「益」字直接，聽音檔反推本調標記可否？

秀容老師嘛毋知彼字ê意思，所以當做語助詞。
是講敢有語助詞會變調?

**Comment by a8568730** [comment]
@naphing 我更新我kah老師的對話矣。
我這馬想想咧，老師應該叫是我欲問彼字若孤字欲按怎唸...

**Comment by naphing** [comment]
這樣就維持作者用「益」字 iah音不需更動?
但秀容老師的發音不到4調，偏3調

**Comment by sih4sing5hong5** [comment]
@a8568730 敢ē-sái koh麻煩你問，是
1. Iah kak-hue-á# suah piàn-kah tsiok ba̍k-thâu# kuân#.
2. Iah# kak-hue-á# suah piàn-kah tsiok ba̍k-thâu# kuân#.

**Comment by a8568730** [comment]
若按呢，老師建議阮咧唸這句的時，

「益」角花仔煞變甲足目頭懸

應該愛唸下面佗一款講法咧？
（#表示彼字是本調）

1. Iah kak-hue-á# suah piàn-kah tsiok ba̍k-thâu# kuân#.

2. Iah# kak-hue-á# suah piàn-kah tsiok ba̍k-thâu# kuân#.

**Comment by sih4sing5hong5** [comment]
這可能就lio̍k毋著--ah，可能愛重錄
@naphing 你勾`NG句`

**Comment by a8568730** [comment]
阿叔講伊攏唸 XD
```
ia̍h tshun# / iā tshun#
```

**Comment by naphing** [comment]
> 這可能就lio̍k毋著--ah，可能愛重錄
> @naphing 你勾`NG句`

DONE
