### ISSUE TITLE
有備註，無確定ê愛提出來討論

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#90]
Tshan像

580  | 直直拚暝工，欲予這陣人傱忝死才甘願呢？ | Ti̍t-ti̍t piànn-mê-kang, beh hōo tsit tīn lâng tsông thiám--sí tsiah kam-guān--nih? |   | tsőng/tsông/傱 |   | 2019年1月15日 18:48
-- | -- | -- | -- | -- | -- | --

304 | 陳先生你好，身軀佗位無爽快？ | Tân--sian-sinn lí hó, sing-khu tó-uī bô sóng-khuài? | 4 | 身sin/sing | [字：身 sing] | 2019年1月7日 13:40
-- | -- | -- | -- | -- | -- | --

**Comment by naphing** [comment]
這兩筆已搞定，掰

**Comment by sih4sing5hong5** [comment]
這兩筆以外閣有[tsiânn濟筆](https://媠聲服務.意傳.台灣/admin/SuiSiannAdminApp/%E5%8F%A5%E8%A1%A8/?o=-5.7.1)？

**Comment by sih4sing5hong5** [comment]
攏巡過--ah
