### ISSUE TITLE
呔會thai3 e7

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#92]
教典有該詞，但程式檢查顯示錯誤咧

例句956
「呔會有遮爾仔好空的代誌？誠實是愛講耍笑！」
"Thài ē ū tsiah-nī-á hó-khang ê tāi-tsì? Tsiânn-si̍t sī ài kóng-sńg-tshiò!"

[教典：呔會](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=14081&curpage=1&sample=%E5%91%94%E6%9C%83&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=1l)

**Comment by sih4sing5hong5** [comment]
最近才加ê詞，請 @a8568730 更新教典字表
https://github.com/g0v/moedict-data-twblg/pull/32/files#diff-25059f1b60308db68555d7866714ff32R14045

**Comment by a8568730** [comment]
好矣。
![image](https://user-images.githubusercontent.com/6355592/51673690-9b12b600-2009-11e9-99f5-7cfe108f8995.png)
