### ISSUE TITLE
共攏總唸做合音的tsőng

### ISSUE THREAD

**Issue by a8568730** [Sui-Siann-Dataset/Sui-Siann-Dataset#94]
需要確定有這音
580
Ti̍t-ti̍t piànn-mê-kang, beh hōo tsit tīn lâng tsőng thiám--sí tsiah kam-guān--nih?
581
Ti̍t-ti̍t piànn-mê-kang, beh hōo tsit tīn lâng tsóng thiám--sí tsiah kam-guān--nih?

**Comment by a8568730** [comment]
失控的台語課 2017年8月2日

[臺語字詞分享 (48) ](https://www.facebook.com/taigikho/photos/a.943692265684759/1374179472636034/?type=3&theater)
--

如圖，「說溜嘴」，臺語常常這樣說。

►圖中例句引讀〉 https://youtu.be/gBxSaVay-mE
　
※ 例句譯文【川仔說溜嘴，就這樣說了出來，害我們現在有得忙了(處理善後)！】
　
　
註❶〔踏脫〕(ta̍h-thu̍t)：(1) 踩空、腳滑 (2) 出差錯、受挫。
　
註❷〔𠱴〕(tsua̋nn / tsua̋n / tsia̋n / tsa̋n / tsőng / tsűn / tsue̋nn / tse̋nn)：合音字，請見〔 https://goo.gl/PFo44s 〕。
　
註❸ 圖例：【TL】臺羅、【POJ】白話字。
　
　
#臺語字詞分享_TâiGíJīSûHunHióng (←點下去可回顧本系列其他分享)

**Comment by a8568730** [comment]
> 註❷〔𠱴〕(tsua̋nn / tsua̋n / tsia̋n / tsa̋n / tsőng / tsűn / tsue̋nn / tse̋nn)：合音字，請見〔 https://goo.gl/PFo44s 〕。

會連對教典的「就按呢」。

詞目 | 就按呢
-- | --
音讀 | tsiū-án-ne　又唸作tsū-án-ne　合音唸作tsua̋n-ne、tsua̋n
釋義 | 1.就這樣子。依照指示。例：代誌就按呢進行。Tāi-tsì tsiū-án-ne tsìn-hîng. (事情就這樣子去做。)　2.因此、所以。用來連結上下文的因果關係。例：伊行無好勢，就按呢跋倒。I kiânn bô hó-sè, tsiū-án-ne pua̍h-tó. (他沒走好，所以跌倒。)

**Comment by naphing** [comment]
所以是「就按呢」的另一種合音，不是「攏總」吧？（跟例句語意不合）

**Comment by a8568730** [comment]
應該是「就按呢」。
無「攏總」的合音應該嘛較倚「l」起頭的音

**Comment by sih4sing5hong5** [comment]
@a8568730  所以咱ê書寫直接`tsőng`就好--ah？

**Comment by naphing** [comment]
無錯！tsőng定案

**Comment by sih4sing5hong5** [comment]
符合 #80 ê 規則，無另外整理到hackmd
