### ISSUE TITLE
身軀sin/sing

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Sui-Siann-Dataset#97]
方言差，是給程式補音處理？
秀容老師多半念sing，偶有sin
[教典-身軀](https://twblg.dict.edu.tw/holodict_new/cuankho.jsp?no=0906)

**Comment by sih4sing5hong5** [comment]
請 @a8568730 更新用字 #98

**Comment by a8568730** [comment]
好，按呢這个ISSUE就徙去 #98 處理。
